// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkjkMi0kdIbFrw0LaClESAVVtaOyOlTYQ',
    appId: '1:1008767757913:web:a864caba8daef812310b48',
    messagingSenderId: '1008767757913',
    projectId: 'fire-crud-11',
    authDomain: 'fire-crud-11.firebaseapp.com',
    storageBucket: 'fire-crud-11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8nXetqeRx7ZvBtwPzEql6x7PdL4552DU',
    appId: '1:1008767757913:android:9061053003bd94ee310b48',
    messagingSenderId: '1008767757913',
    projectId: 'fire-crud-11',
    storageBucket: 'fire-crud-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAz_7I4BKtJNgTuiduK0grm6yJout_9-c',
    appId: '1:1008767757913:ios:9b11e17635912306310b48',
    messagingSenderId: '1008767757913',
    projectId: 'fire-crud-11',
    storageBucket: 'fire-crud-11.appspot.com',
    iosBundleId: 'com.nehal.newfireproject.newfireproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAz_7I4BKtJNgTuiduK0grm6yJout_9-c',
    appId: '1:1008767757913:ios:9b11e17635912306310b48',
    messagingSenderId: '1008767757913',
    projectId: 'fire-crud-11',
    storageBucket: 'fire-crud-11.appspot.com',
    iosBundleId: 'com.nehal.newfireproject.newfireproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkjkMi0kdIbFrw0LaClESAVVtaOyOlTYQ',
    appId: '1:1008767757913:web:2f01ce391341d83e310b48',
    messagingSenderId: '1008767757913',
    projectId: 'fire-crud-11',
    authDomain: 'fire-crud-11.firebaseapp.com',
    storageBucket: 'fire-crud-11.appspot.com',
  );
}
